name: portable_radio
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  async: ^2.13.0
  dio: ^5.9.0
  flutter_bloc: ^9.1.1
  flutter_oknob: ^0.0.5
  freezed_annotation: ^3.0.0
  get_it: ^8.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^2.4.0
  intl: ^0.20.2
  just_audio: ^0.10.5
  miv_buttons: ^1.0.1
  path_provider: ^2.1.5
  very_good_cli: ^0.17.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  alchemist: ^0.12.1
  bloc_test: ^10.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.4
  build_runner: ^2.4.10
  freezed: ^3.0.0
  injectable_generator: ^2.4.0
  json_serializable: ^6.8.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  generate: true

scripts: derry.yaml
