name: portable_radio
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^5.9.0
  flutter_oknob: ^0.0.5
  freezed_annotation: ^3.1.0
  get_it: ^8.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^2.5.2
  intl: ^0.20.2
  just_audio: ^0.10.5
  miv_buttons: ^1.0.1
  path_provider: ^2.1.5
  very_good_cli: ^0.17.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.9.0
  freezed: ^3.2.3
  injectable_generator: ^2.9.0
  json_serializable: ^6.11.1
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  generate: true

scripts: derry.yaml
